# Generated by Django 4.1.7 on 2023-03-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
